apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r7x6cm335-go 
  janus-idp.io/tekton: r7x6cm335-go
  backstage.io/kubernetes-id: r7x6cm335-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r7x6cm335-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml